import { useEffect, useState } from "react";

import "../styles/dashboard.css";

import Nav from "../components/nav";
import Match from "../components/match";
import QRgen from "../components/qrgen";
import ButtonBar from "../components/button-bar";

import {
  getEventFromKey,
  getEventsFromWeek,
  getMatchesFromEventKey,
} from "../api/tba";
import { storeMatchSchedule, loadMatchSchedules } from "../api/local-storage";

import { IEvent, IMatchSchedule } from "../models";

export default function Dashboard({ setEId, setEWeek }) {
  const [eventList, setEventList] = useState<Array<IEvent> | null>(); // the list of events that is rendered in the dropdown (pulled from TBA or ls)
  const [localLen, setLocalLen] = useState(0); // number of local matches in event list
  const [matchSchedule, setMatchSchedule] = useState<IMatchSchedule>([]); // the list of matches (pulled from TBA or ls)
  const [week, setWeek] = useState(1); // the week currently seleceted in the dropdown
  const [eventKey, setEventKey] = useState(""); // the event id of the currently selected event (generated by TBA)
  const [showQRgen, setShowQRgen] = useState(false); // wheather the QR code is displayed
  const [QRdata, setQRdata] = useState({}); // the data to display in the QR code
  const [lockDropdown, setLockDropdown] = useState(false); // wheather to lock changes to the dropdowns

  useEffect(() => {
    // This function runs after the page loads or when `week` is changed. It calls ls or TBA to get the list of events for that week.
    if (navigator.onLine) {
      // runs while online
      setEWeek(week);
      getEventsFromWeek(week).then((s) => {
        loadMatchSchedules(week).then((l) => {
          if (l?.length > 0) {
            setEventList([...s, ...l]); // add local nmatches to event list
            setLocalLen(l.length);
          } else {
            setEventList(s);
          }

          setEventKey(s[0].id);
        });
      });
    } else {
      // runs while offline
      loadMatchSchedules(week).then((s) => {
        setEventList(s);
        setEventKey(s[0].id);
      });
    }
  }, [week]);

  useEffect(() => {
    // This function runs after the page loads or when `eventKey` is changed. It calls ls or TBA to get the match schedule.
    if (navigator.onLine) {
      // runs while online
      setEId(eventKey);
      getMatchesFromEventKey(eventKey)
        .then((s) => {
          setMatchSchedule(s);
          getEventFromKey(eventKey).then((res) =>
            storeMatchSchedule(week, res)
          ); // stores selected match in ls
        })
        .catch((err) => {
          // assuming error is that match is local, so pull matches from local storage
          const s: any = eventList
            ? eventList.find((x) => x.id === eventKey)?.matches
            : [];
          if (s.length > 0) setMatchSchedule(s);
        });
    } else {
      // runs while offline
      const s: any = eventList
        ? eventList.find((x) => x.id === eventKey)?.matches // get the event from eventList that has our selected match key
        : [];
      if (s.length > 0) {
        setMatchSchedule(s);
      } // if we have a match, set the match schedule
    }
    // eslint-disable-next-line
  }, [eventKey]);

  return (
    <div>
      {showQRgen ? (
        <QRgen exit={() => setShowQRgen(false)} data={QRdata} />
      ) : (
        <></>
      )}
      <div
        style={{
          margin: "0 1rem",
          marginTop: "1.5rem",
        }}
      >
        <select
          value={week}
          id="week-select"
          onChange={(e) => setWeek(parseInt(e.target.value))}
          disabled={lockDropdown}
        >
          <option value={1}>Week 1</option>
          <option value={2}>Week 2</option>
          <option value={3}>Week 3</option>
          <option value={4}>Week 4</option>
          <option value={5}>Week 5</option>
          <option value={6}>Week 6</option>
        </select>

        {/* eventKey is a prop needed for the csv viewer*/}
        <ButtonBar
          lockDropdown={lockDropdown}
          lock={() => setLockDropdown(true)}
          unlock={() => setLockDropdown(false)}
          eventKey={eventKey}
          week={week}
        />
      </div>
      <select
        value={eventKey}
        name="Event"
        id="event-select"
        onChange={(m) => setEventKey(m.target.value)}
        disabled={lockDropdown}
      >
        {eventList ? (
          eventList.map((e, i) => (
            <option value={e.id} key={i}>
              {i === eventList.length - localLen ? "**LOCAL EVENTS: " : ""}
              {e.name}
            </option>
          ))
        ) : (
          <></>
        )}
      </select>

      <hr />

      <div className="matches">
        <p>Matches</p>
      </div>

      <div>
        {matchSchedule.length > 0 ? (
          matchSchedule.map((data, index) => (
            <Match
              key={index}
              matchData={data}
              openQRgen={(QRinfo) => {
                setShowQRgen(true);
                setQRdata(QRinfo);
              }}
            />
          ))
        ) : (
          <></>
        )}
      </div>
      <Nav selectedPage={1} />
    </div>
  );
}
